############################################################
# Ping Identity
#
############################################################


global:
  image:
    tag: "edge"  # Uses images with the "edge" tag

pingdataconsole:
  enabled: true

#pingdatagovernance:
#  enabled: true

pingdirectory:
  enabled: true
  envs:
    SERVER_PROFILE_URL: https://github.com/chrisleggett/k8s-banking-demo.git
    SERVER_PROFILE_PATH: server-profiles/pingdirectory
